### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [Stanleey/prj-rev-bwfs-dasmoto#7]
https://github.com/Stanleey/prj-rev-bwfs-dasmoto/blob/master/project_helloCss/resources/style.css#L11-L16

You're repeating a lot of styles in these three CSS rules.

When you have some styles that need to get applied to several elements, write them in a single rule with a more general selector. For example:

```css
* {
  font-family: Helvetica;
}

.product h2 {
  font-size: 32px;
  font-weight: bold;
  color: white;
}

#brushes {
  background-color: mediumspringgreen;
}
```
